### ISSUE TITLE
predicted values: sensitive versus non-sensitive

### ISSUE THREAD

**Issue by RoelTim** [neerbek/taboo-core#2]
Hi @neerbek,

I have one other question. I have been puzzling around a lot to get the sensitivity predictions on new data: 4 (sensitive) versus 0 (non-sensitive).

I know that with Theano it is not straightforward to get the actual predicted values.

Although you are not working on this project anymore, do you remember how you did this?

It would be great if you could help me,
Roelien

**Comment by neerbek** [comment]
Hi Roelien,
sorry for the delay in answer.
If you just want to inspect the output probabilities you can use the run_model_verbose.py command (args are same format as for the run_mode.py command in my previous answer https://github.com/neerbek/taboo-core/issues/1#issuecomment-734744542)

So
OMP_NUM_THREADS=2 ipython3 functionality/run_model_verbose.py -- -inputtrees 201/dev_custom250_random.txt -inputmodel save_best.txt -nx 50 -nh 100 -batch_size 1000 -glove_path tests/resources/glove/  > output.txt

The last part "> output.txt" redirect the verbose output to output.txt
For each sample in your input (here 201/dev_custom250_random.txt) you get a line
1	0	1	0.18360182923439158	14	 MDEA is a joint action agency formed by the Cities pursuant to Mississippi law.	 (0 (0 (0 MDEA) (0 (0 is) (0 (0 (0 a) (0 (0 joint) (0 (0 action) (0 agency)))) (0 (0 formed) (0 (0 by) (0 (0 (0 the) (0 (0 Cities) (0 pursuant))) (0 (0 to) (0 (0 Mississippi) (0 law))))))))) (0 .))

which is on the format
Index	Truth	Is_Accurate	ProbSen	Size	Sentence	Tree

where Index is just number of sample, Truth is whether sentence is labelled sensitive (0=False, 1=True)
is_Accurate says if your model (here save_best.txt) is accurate on this sample (0=False, 1=True)
ProbSen is the probability (softmax weight) from model of sample having label 1 (i.e. being sensitive)
Size is word count in sentence, Sentence is sentence and Tree is input tree

Does this answer you question? :)

**Comment by RoelTim** [comment]
It's all clear now. Big thanks for explaining.
